apiVersion: v1
kind: Service
metadata:
  name: {{ include "swns.db.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "swns.db.labels" . | nindent 4 }}
spec:
  type: {{ .Values.dbService.type }}
  ports:
    - port: {{ .Values.dbService.port }}
      targetPort: {{ .Values.dbService.port }}
      protocol: TCP
  selector:
    {{- include "swns.db.selectorLabels" . | nindent 4 }}