apiVersion: v1
kind: Secret
metadata:
  name: {{ include "swns.fullname" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- range $key, $val := .Values.django.secret }}
    {{ $key }}: {{ $val | toString | b64enc | quote }}
  {{- end }}