apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "swns.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  DB_HOST: {{ include "swns.db.fullname" . }}
  DJANGO_SETTINGS_MODULE: {{ .Values.django.configMap.DJANGO_SETTINGS_MODULE }}