apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "swns.db.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nks-block-storage