name: CI

on:
    pull_request:
        types:
            closed
    release:
        types:
            - published

env:
    IMAGE: ${{ vars.NCR_HOST }}/swns
    IMAGE_TAG: ${{ vars.NCR_HOST }}/swns:latest

jobs:
    build-and-push:
        name: build image
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set up Docker buildx
              uses: docker/setup-buildx-action@v2
            
            - name: Login to NCR
              uses: docker/login-action@v2
              with:
                registry: ${{ vars.NCR_HOST }}
                username: ${{ secrets.NCP_ACCESS_KEY }}
                password: ${{ secrets.NCP_SECRET_KEY }}
            
            - name: Get current timestamp
              id: image-tag
              run: echo "TIMESTAMP=$(date "+%s")" >> "$GITHUB_OUTPUT"

            - name: Build and Push
              if: startsWith(github.ref, 'refs/heads')
              uses: docker/build-push-action@v4
              with:
                context: .
                tags: ${{ env.IMAGE_TAG }}, ${{ env.IMAGE }}:${{ steps.image-tag.outputs.TIMESTAMP }}
                file: ./docker/Dockerfile_dj
                push: true

            - name: Build and Push
              if: startsWith(github.ref, 'refs/tags')
              uses: docker/build-push-action@v4
              with:
                context: .
                tags: ${{ env.IMAGE }}:${{ github.event.release.tag_name }}
                file: ./docker/Dockerfile_dj
                push: true
