name: CI and CD to prod server using Docker Image

on:
    release:
        types:
            - published


env:
    IMAGE: ${{ vars.NCR_HOST }}/swns
    IMAGE_TAG: ${{ vars.NCR_HOST }}/lion-app:latest
    CONTAINER_NAME: be-prod

jobs:
    build-push:
        name: build image
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            
            - name: Login to NCR
              uses: docker/login-action@v2
              with:
                registry: ${{ vars.NCR_HOST }}
                username: ${{ secrets.NCP_ACCESS_KEY }}
                password: ${{ secrets.NCP_SECRET_KEY }}
            
            - name: Get current timestamp
              id: image-tag
              run: echo "TIMESTAMP=$(date "+%s")" >> "$GITHUB_OUTPUT"

            - name: Build and Push
              uses: docker/build-push-action@v4
              with:
                context: .
                tags: ${{ env.IMAGE_TAG }}, ${{ env.IMAGE }}:${{ github.event.release.tag_name }}
                file: ./docker/Dockerfile_dj
                push: true

    deploy-prod:
        needs: build-push
        name: deploy to prod
        runs-on: ubuntu-latest
        steps:
            - name: checkout repository
              uses: actions/checkout@v4
            - name: pull and run the image
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: ${{ vars.NCP_HOST_PROD }}
                  username: ${{ secrets.SSH_USERNAME }}
                  password: ${{ secrets.SSH_PASSWORD }}
                  script: |
                      docker login \
                      ${{ vars.NCR_HOST }} \
                      -u ${{ secrets.NCP_ACCESS_KEY }} \
                      -p ${{ secrets.NCP_SECRET_KEY }}
                      docker pull ${{ env.IMAGE }}:${{ github.event.release.tag_name }}
                      docker stop ${{ env.CONTAINER_NAME }} && docker rm ${{ env.CONTAINER_NAME }}
                      docker run -d -p 8000:8000 \
                      --env-file .env \
                      --name ${{ env.CONTAINER_NAME }} \
                      ${{ env.IMAGE }}:${{ github.event.release.tag_name }}
